### ISSUE TITLE
VTT speakers and paragraphs export broken 

### ISSUE THREAD

**Issue by pietrop** [pietrop/slate-transcript-editor#28]
**Describe the bug**

VTT speakers and paragraphs export broken 

**To Reproduce**
1. Go to storybook http://localhost:6006
2. Click on `CC` captions button
3. Click on `VTT with speakers and paragraphs`

in console
```js
index.js:35 Uncaught (in promise) TypeError: Cannot read property 'end' of undefined
    at index.js:35
    at Array.map (<anonymous>)
    at addTimecodesToLines (index.js:30)
    at preSegmentTextJson (index.js:88)
    at subtitlesComposer (index.js:92)
    at _callee6$ (index.js:457)
    at tryCatch (runtime.js:63)
    at Generator.invoke [as _invoke] (runtime.js:293)
    at Generator.next (runtime.js:118)
    at asyncGeneratorStep (4-Live.stories.js:111)
```

line 35 in `addTimecodesToLines` in [`/src/util/export-adapters/subtitles-generator/index.js#35`](https://github.com/pietrop/slate-transcript-editor/blob/update-timestamps/src/util/export-adapters/subtitles-generator/index.js#L35)

```js
jsonLine.end = wordsList[endWordCounter - 1].end;
```
**Expected behavior**

To be able to export with `VTT with speakers and paragraphs`
**Additional context**

_NA_

**Comment by overZellis133** [comment]
@jshearer

**Comment by jshearer** [comment]
@pietrop this can be closed now right?

**Comment by pietrop** [comment]
yup, good catch, thanks
