### ISSUE TITLE
typo 

### ISSUE THREAD

**Issue by pietrop** [pietrop/slate-transcript-editor#33]
```diff
- <style scope>
+ <style scoped>
```
[/src/components/index.js#L457](https://github.com/pietrop/slate-transcript-editor/blob/2e0fcf7d220ee3b9289be000ef9ed015ec725f3b/src/components/index.js#L457)

**Comment by 96RadhikaJadhav** [comment]
@pietrop  Can I work on the issue?

**Comment by pietrop** [comment]
👋 @96RadhikaJadhav 
Absolutely, feel free to do a PR 😁
